force-app/main/default/objects/Holidays_Conf__mdt/Holidays_Conf__mdt.object-meta.xml
<CustomObject>
    <label>Holidays Conf</label>
    <pluralLabel>Holidays Confs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Holidays_Conf__mdt/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>ClassName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HolidaysDispatcher.cls
public with sharing class HolidaysDispatcher {
    public static double getHolidaysBonus(Id empId, String country){
        List<Holidays_Conf__mdt> confMetadata = [
            SELECT ClassName__c 
            FROM Holidays_Conf__mdt 
            WHERE DeveloperName = :country AND ClassName__c != NULL WITH SECURITY_ENFORCED LIMIT 1];
        if (confMetadata.isEmpty()){
            //Agrego esto para que se vea más clara la diferencia.
            HolidaysFixedBonus holClass = new HolidaysFixedBonus();
            return holClass.calculateBonus(empId);
        }
        else{
            Type t = Type.forName(confMetadata[0].ClassName__c);
            HolidaysInterface holidayClass = (HolidaysInterface)t.newInstance();
            return holidayClass.calculateBonus(empId);
        }    
    }
}